type PrefillEntry = { day: string; startTime: string; label: string; bg?: string; textColor?: string; disableClick?: boolean };

function makePrefill(rows: Record<string, string[]>) {
  const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  return Object.entries(rows).flatMap(([startTime, labels]) =>
    days.flatMap((day, dayIndex) => labels[dayIndex] ? [{ day, startTime, label: labels[dayIndex] }] : [])
  );
}

const imagePrefill: Record<string, PrefillEntry[]> = {
  DESCARTES: [
    { day: "Monday", startTime: "07:45", label: "UCSP" },
    { day: "Tuesday", startTime: "07:45", label: "UCSP" },
    { day: "Wednesday", startTime: "07:45", label: "UCSP" },
    { day: "Thursday", startTime: "07:45", label: "UCSP" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Thursday", startTime: "08:45", label: "READING & WRITING" },
    { day: "Friday", startTime: "08:45", label: "PR1" },
    { day: "Monday", startTime: "10:00", label: "EIM" },
    { day: "Tuesday", startTime: "10:00", label: "HOPE" },
    { day: "Wednesday", startTime: "10:00", label: "EIM" },
    { day: "Thursday", startTime: "10:00", label: "EIM" },
    { day: "Friday", startTime: "10:00", label: "EIM" },
    { day: "Monday", startTime: "11:00", label: "EIM" },
    { day: "Tuesday", startTime: "11:00", label: "PAGBASA" },
    { day: "Wednesday", startTime: "11:00", label: "EIM" },
    { day: "Thursday", startTime: "11:00", label: "EIM" },
    { day: "Friday", startTime: "11:00", label: "EIM" },
    { day: "Monday", startTime: "13:00", label: "PhySci" },
    { day: "Tuesday", startTime: "13:00", label: "PhySci" },
    { day: "Wednesday", startTime: "13:00", label: "PhySci" },
    { day: "Thursday", startTime: "13:00", label: "STAT" },
    { day: "Friday", startTime: "13:00", label: "PhySci" },
    { day: "Monday", startTime: "14:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "14:00", label: "STAT" },
    { day: "Wednesday", startTime: "14:00", label: "PR1" },
    { day: "Thursday", startTime: "14:00", label: "PR1" },
    { day: "Friday", startTime: "14:00", label: "STAT" },
    { day: "Monday", startTime: "15:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "15:00", label: "STAT" },
    { day: "Wednesday", startTime: "15:00", label: "PAGBASA" },
    { day: "Thursday", startTime: "15:00", label: "PR1" },
    { day: "Friday", startTime: "15:00", label: "HOPE" },
  ],
  PHYTAGORAS: [
    { day: "Friday", startTime: "07:45", label: "STAT" },
    { day: "Friday", startTime: "08:45", label: "READING & WRTING" },
    { day: "Friday", startTime: "10:00", label: "BNC" },
    { day: "Friday", startTime: "11:00", label: "BNC" },
    { day: "Friday", startTime: "13:00", label: "UCSP" },
    { day: "Friday", startTime: "14:00", label: "PhySci" },
    { day: "Friday", startTime: "15:00", label: "PAGBASA" },
    { day: "Friday", startTime: "16:00", label: "HOPE" },
    { day: "Friday", startTime: "17:00", label: "PR1" },
  ],
  KANT: [
    { day: "Monday", startTime: "07:45", label: "PAGBASA" },
    { day: "Tuesday", startTime: "07:45", label: "PAGBASA" },
    { day: "Wednesday", startTime: "07:45", label: "PAGBASA" },
    { day: "Thursday", startTime: "07:45", label: "PAGBASA" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "PR" },
    { day: "Tuesday", startTime: "08:45", label: "PR" },
    { day: "Wednesday", startTime: "08:45", label: "PR" },
    { day: "Thursday", startTime: "08:45", label: "PR" },
    { day: "Friday", startTime: "08:45", label: "PHYSCI" },
    { day: "Monday", startTime: "10:00", label: "BNC" },
    { day: "Tuesday", startTime: "10:00", label: "BNC" },
    { day: "Wednesday", startTime: "10:00", label: "HOPE" },
    { day: "Thursday", startTime: "10:00", label: "BNC" },
    { day: "Friday", startTime: "10:00", label: "BNC" },
    { day: "Monday", startTime: "11:00", label: "BNC" },
    { day: "Tuesday", startTime: "11:00", label: "BNC" },
    { day: "Wednesday", startTime: "11:00", label: "PHYSCI" },
    { day: "Thursday", startTime: "11:00", label: "BNC" },
    { day: "Friday", startTime: "11:00", label: "BNC" },
    { day: "Monday", startTime: "13:00", label: "STAT" },
    { day: "Tuesday", startTime: "13:00", label: "STAT" },
    { day: "Wednesday", startTime: "13:00", label: "STAT" },
    { day: "Thursday", startTime: "13:00", label: "PHYSCI" },
    { day: "Friday", startTime: "13:00", label: "STAT" },
    { day: "Monday", startTime: "14:00", label: "UCSP" },
    { day: "Tuesday", startTime: "14:00", label: "UCSP" },
    { day: "Wednesday", startTime: "14:00", label: "UCSP" },
    { day: "Thursday", startTime: "14:00", label: "PHYSCI" },
    { day: "Friday", startTime: "14:00", label: "UCSP" },
    { day: "Monday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "15:00", label: "READING & WRITING" },
    { day: "Thursday", startTime: "15:00", label: "READING & WRITING" },
  ],
  ERICKSON: [
    { day: "Monday", startTime: "07:45", label: "PR" },
    { day: "Monday", startTime: "08:45", label: "STAT" },
    { day: "Monday", startTime: "10:00", label: "HOPE" },
    { day: "Monday", startTime: "11:00", label: "UCSP" },
    { day: "Monday", startTime: "13:00", label: "READING & WRITING" },
    { day: "Monday", startTime: "14:00", label: "BNC" },
    { day: "Monday", startTime: "15:00", label: "BNC" },
    { day: "Tuesday", startTime: "07:45", label: "PR" },
    { day: "Tuesday", startTime: "08:45", label: "STAT" },
    { day: "Tuesday", startTime: "10:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "11:00", label: "UCSP" },
    { day: "Tuesday", startTime: "13:00", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "14:00", label: "BNC" },
    { day: "Tuesday", startTime: "15:00", label: "BNC" },
    { day: "Wednesday", startTime: "07:45", label: "PR" },
    { day: "Wednesday", startTime: "08:45", label: "STAT" },
    { day: "Wednesday", startTime: "10:00", label: "PhySci" },
    { day: "Wednesday", startTime: "11:00", label: "UCSP" },
    { day: "Wednesday", startTime: "13:00", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "14:00", label: "BNC" },
    { day: "Wednesday", startTime: "15:00", label: "BNC" },
    { day: "Thursday", startTime: "07:45", label: "PR" },
    { day: "Thursday", startTime: "08:45", label: "PAGBASA" },
    { day: "Thursday", startTime: "10:00", label: "PhySci" },
    { day: "Thursday", startTime: "11:00", label: "UCSP" },
    { day: "Thursday", startTime: "13:00", label: "READING & WRITING" },
    { day: "Thursday", startTime: "14:00", label: "BNC" },
    { day: "Thursday", startTime: "15:00", label: "BNC" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Friday", startTime: "08:45", label: "STAT" },
    { day: "Friday", startTime: "10:00", label: "PhySci" },
    { day: "Friday", startTime: "11:00", label: "PhySci" },
    { day: "Friday", startTime: "13:00", label: "PAGBASA" },
    { day: "Friday", startTime: "14:00", label: "PAGBASA" },
  ],
  HONESTY: [
    { day: "Monday", startTime: "07:45", label: "IMMERSION" },
    { day: "Tuesday", startTime: "07:45", label: "IMMERSION" },
    { day: "Wednesday", startTime: "07:45", label: "IMMERSION" },
    { day: "Thursday", startTime: "07:45", label: "IMMERSION" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "PERDEV" },
    { day: "Tuesday", startTime: "08:45", label: "PERDEV" },
    { day: "Wednesday", startTime: "08:45", label: "PERDEV" },
    { day: "Thursday", startTime: "08:45", label: "PERDEV" },
    { day: "Friday", startTime: "08:45", label: "EAPP" },
    { day: "Monday", startTime: "10:00", label: "FBS" },
    { day: "Tuesday", startTime: "10:00", label: "EAPP" },
    { day: "Wednesday", startTime: "10:00", label: "FBS" },
    { day: "Thursday", startTime: "10:00", label: "FBS" },
    { day: "Friday", startTime: "10:00", label: "FBS" },
    { day: "Monday", startTime: "11:00", label: "FBS" },
    { day: "Tuesday", startTime: "11:00", label: "HOPE" },
    { day: "Wednesday", startTime: "11:00", label: "FBS" },
    { day: "Thursday", startTime: "11:00", label: "FBS" },
    { day: "Friday", startTime: "11:00", label: "FBS" },
    { day: "Monday", startTime: "13:00", label: "MIL" },
    { day: "Tuesday", startTime: "13:00", label: "MIL" },
    { day: "Wednesday", startTime: "13:00", label: "MIL" },
    { day: "Thursday", startTime: "13:00", label: "EAPP" },
    { day: "Friday", startTime: "13:00", label: "3Is" },
    { day: "Monday", startTime: "14:00", label: "3Is" },
    { day: "Tuesday", startTime: "14:00", label: "3Is" },
    { day: "Wednesday", startTime: "14:00", label: "MIL" },
    { day: "Thursday", startTime: "14:00", label: "EAPP" },
    { day: "Friday", startTime: "14:00", label: "3Is" },
  ],
  SIMPLICITY: makePrefill({
    "07:45": ["EIM", "EIM", "EIM", "HRGP", "EIM"],
    "08:45": ["EIM", "EIM", "EIM", "HOPE", "EIM"],
    "10:00": ["EAPP", "EAPP", "3Is", "EAPP", "EAPP"],
    "11:00": ["3Is", "3Is", "MIL", "MIL", "3Is"],
    "13:00": ["PERDEV", "PERDEV", "PERDEV", "PERDEV", "MIL"],
    "14:00": ["IMMERSION", "IMMERSION", "IMMERSION", "IMMERSION", "MIL"],
  }),
  DEWEY: [
    { day: "Monday", startTime: "07:45", label: "EIM" },
    { day: "Tuesday", startTime: "07:45", label: "EIM" },
    { day: "Wednesday", startTime: "07:45", label: "EIM" },
    { day: "Thursday", startTime: "07:45", label: "EIM" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },
    { day: "Monday", startTime: "08:45", label: "EIM" },
    { day: "Tuesday", startTime: "08:45", label: "EIM" },
    { day: "Wednesday", startTime: "08:45", label: "EIM" },
    { day: "Thursday", startTime: "08:45", label: "EIM" },
    { day: "Friday", startTime: "08:45", label: "PhySci" },
    { day: "Monday", startTime: "10:00", label: "STAT" },
    { day: "Tuesday", startTime: "10:00", label: "STAT" },
    { day: "Wednesday", startTime: "10:00", label: "PR" },
    { day: "Thursday", startTime: "10:00", label: "STAT" },
    { day: "Friday", startTime: "10:00", label: "STAT" },
    { day: "Monday", startTime: "11:00", label: "PhySci" },
    { day: "Tuesday", startTime: "11:00", label: "PR" },
    { day: "Wednesday", startTime: "11:00", label: "HOPE" },
    { day: "Thursday", startTime: "11:00", label: "PR" },
    { day: "Friday", startTime: "11:00", label: "PR" },
    { day: "Monday", startTime: "13:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "13:00", label: "PAGBASA" },
    { day: "Wednesday", startTime: "13:00", label: "READING & WRITING" },
    { day: "Thursday", startTime: "13:00", label: "PAGBASA" },
    { day: "Friday", startTime: "13:00", label: "PAGBASA" },
    { day: "Monday", startTime: "14:00", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "14:00", label: "PhySci" },
    { day: "Wednesday", startTime: "14:00", label: "READING & WRITING" },
    { day: "Thursday", startTime: "14:00", label: "UCSP" },
    { day: "Friday", startTime: "14:00", label: "READING & WRITING" },
    { day: "Monday", startTime: "15:00", label: "UCSP" },
    { day: "Tuesday", startTime: "15:00", label: "PhySci" },
    { day: "Wednesday", startTime: "15:00", label: "UCSP" },
    { day: "Thursday", startTime: "15:00", label: "UCSP" },
  ],
  SOCRATES: [
    { day: "Monday", startTime: "07:45", label: "DRRR" },
    { day: "Tuesday", startTime: "07:45", label: "DRRR" },
    { day: "Wednesday", startTime: "07:45", label: "DRRR" },
    { day: "Thursday", startTime: "07:45", label: "DRRR" },
    { day: "Friday", startTime: "07:45", label: "HRGP" },

    { day: "Monday", startTime: "08:45", label: "HOPE" },
    { day: "Tuesday", startTime: "08:45", label: "UCSP" },
    { day: "Wednesday", startTime: "08:45", label: "UCSP" },
    { day: "Thursday", startTime: "08:45", label: "UCSP" },
    { day: "Friday", startTime: "08:45", label: "UCSP" },

    { day: "Monday", startTime: "10:00", label: "GEN BIO 2" },
    { day: "Tuesday", startTime: "10:00", label: "BASIC CALCULUS" },
    { day: "Wednesday", startTime: "10:00", label: "BASIC CALCULUS" },
    { day: "Thursday", startTime: "10:00", label: "BASIC CALCULUS" },
    { day: "Friday", startTime: "10:00", label: "BASIC CALCULUS" },

    { day: "Monday", startTime: "11:00", label: "READING & WRITING" },
    { day: "Tuesday", startTime: "11:00", label: "READING & WRITING" },
    { day: "Wednesday", startTime: "11:00", label: "GEN BIO 2" },
    { day: "Thursday", startTime: "11:00", label: "READING & WRITING" },
    { day: "Friday", startTime: "11:00", label: "READING & WRITING" },

    { day: "Monday", startTime: "13:00", label: "STAT" },
    { day: "Tuesday", startTime: "13:00", label: "STAT" },
    { day: "Wednesday", startTime: "13:00", label: "STAT" },
    { day: "Thursday", startTime: "13:00", label: "STAT" },
    { day: "Friday", startTime: "13:00", label: "GEN BIO 2" },

    { day: "Monday", startTime: "14:00", label: "PAGBASA" },
    { day: "Tuesday", startTime: "14:00", label: "PAGBASA" },
    { day: "Wednesday", startTime: "14:00", label: "PAGBASA" },
    { day: "Thursday", startTime: "14:00", label: "PAGBASA" },
    { day: "Friday", startTime: "14:00", label: "GEN BIO 2" },

    { day: "Monday", startTime: "15:00", label: "PR1" },
    { day: "Tuesday", startTime: "15:00", label: "PR1" },
    { day: "Wednesday", startTime: "15:00", label: "PR1" },
    { day: "Thursday", startTime: "15:00", label: "PR1" },
  ],
  LAOTZU: makePrefill({
    "07:45": ["STAT", "STAT", "STAT", "STAT", "HRGP"],
    "08:45": ["PAGBASA", "HOPE", "PAGBASA", "PAGBASA", "PAGBASA"],
    "10:00": ["READING & WRITING", "GEN BIO", "GEN BIO", "GEN BIO", "GEN BIO"],
    "11:00": ["DRRR", "DRRR", "READING & WRITING", "DRRR", "DRRR"],
    "13:00": ["PR1", "PR1", "PR1", "PR1", "READING & WRITING"],
    "14:00": ["CALCULUS", "CALCULUS", "CALCULUS", "CALCULUS", "READING & WRITING"],
    "15:00": ["UCSP", "UCSP", "UCSP", "UCSP", ""],
  }),
  LOCKE: makePrefill({
    "07:45": ["STAT", "STAT", "STAT", "STAT", "HRGP"],
    "08:45": ["PR1", "PR1", "HOPE", "PR1", "PR1"],
    "10:00": ["PHYSCI", "READING & WRITING", "READING & WRITING", "READING & WRITING", "READING & WRITING"],
    "11:00": ["PAGBASA", "PHYSCI", "PAGBASA", "PAGBASA", "PAGBASA"],
    "13:00": ["CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "UCSP"],
    "14:00": ["DRRR", "DRRR", "DRRR", "DRRR", "PHYSCI"],
    "15:00": ["UCSP", "UCSP", "UCSP", "", "PHYSCI"],
  }),
  VOLTAIRE: makePrefill({
    "07:45": ["PAGBASA", "PAGBASA", "PAGBASA", "PAGBASA", "HRGP"],
    "08:45": ["READING & WRITING", "READING & WRITING", "READING & WRITING", "READING & WRITING", "HOPE"],
    "10:00": ["STAT", "PHYSCI", "PHYSCI", "PHYSCI", "PHYSCI"],
    "11:00": ["STAT", "UCSP", "UCSP", "UCSP", "UCSP"],
    "13:00": ["PR1", "PR1", "PR1", "STAT", "PR1"],
    "14:00": ["CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "STAT"],
    "15:00": ["DRRR", "DRRR", "DRRR", "", "DRRR"],
  }),
  DEMOCRITUS: makePrefill({
    "07:45": ["CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "HRGP"],
    "08:45": ["PHYSCI", "PHYSCI", "PHYSCI", "HOPE", "PHYSCI"],
    "10:00": ["STAT", "UCSP", "UCSP", "UCSP", "UCSP"],
    "11:00": ["STAT", "PAGBASA", "PAGBASA", "PAGBASA", "PAGBASA"],
    "13:00": ["DIAS", "DIAS", "DIAS", "STAT", "DIAS"],
    "14:00": ["READING & WRITING", "READING & WRITING", "READING & WRITING", "READING & WRITING", "PR"],
    "15:00": ["PR", "PR", "PR", "", "STAT"],
  }),
  HUME: makePrefill({
    "07:45": ["UCSP", "UCSP", "UCSP", "UCSP", "HRGP"],
    "08:45": ["STAT", "STAT", "STAT", "DIAS", "STAT"],
    "10:00": ["DIAS", "PHYSCI", "PHYSCI", "PHYSCI", "PHYSCI"],
    "11:00": ["DIAS", "PR1", "PR1", "PR1", "PR1"],
    "13:00": ["HOPE", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING"],
    "14:00": ["READING", "READING", "READING", "READING", "PAGBASA"],
    "15:00": ["PAGBASA", "PAGBASA", "PAGBASA", "", "DIAS"],
  }),
  PLATO: makePrefill({
    "07:45": ["PAGBASA", "PAGBASA", "PAGBASA", "PAGBASA", "HRGP"],
    "08:45": ["DIAS", "DIAS", "DIAS", "DIAS", "PHYSCI"],
    "10:00": ["PHYSCI", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING"],
    "11:00": ["PHYSCI", "STAT", "STAT", "STAT", "STAT"],
    "13:00": ["READING", "HOPE", "READING", "READING", "READING"],
    "14:00": ["UCSP", "UCSP", "UCSP", "PR1", "UCSP"],
    "15:00": ["PR1", "PR1", "PR1", "", "PHYSCI"],
  }),
  CONFUCIUS: makePrefill({
    "07:45": ["PR1", "PR1", "PR1", "PR1", "HRGP"],
    "08:45": ["STAT", "STAT", "STAT", "STAT", "CREATIVE WRITING"],
    "10:00": ["PHYSCI", "READING & WRITING", "READING & WRITING", "READING & WRITING", "READING & WRITING"],
    "11:00": ["PHYSCI", "DIAS", "DIAS", "DIAS", "DIAS"],
    "13:00": ["PAGBASA", "PAGBASA", "HOPE", "PAGBASA", "PAGBASA"],
    "14:00": ["UCSP", "UCSP", "UCSP", "PHYSCI", "UCSP"],
    "15:00": ["CREATIVE WRITING", "CREATIVE WRITING", "CREATIVE WRITING", "", "PHYSCI"],
  }),
  AURELIUS: makePrefill({
    "07:45": ["PAGBASA", "PAGBASA", "PAGBASA", "PAGBASA", "HRGP"],
    "08:45": ["READING & WRITING", "READING & WRITING", "READING & WRITING", "CREATIVE WRITING", "READING & WRITING"],
    "10:00": ["CREATIVE WRITING", "DIAS", "DIAS", "DIAS", "DIAS"],
    "11:00": ["CREATIVE WRITING", "PHYSCI", "PHYSCI", "PHYSCI", "PHYSCI"],
    "13:00": ["STAT", "STAT", "STAT", "HOPE", "STAT"],
    "14:00": ["PR1", "PR1", "PR1", "PR1", "UCSP"],
    "15:00": ["UCSP", "UCSP", "UCSP", "", "CREATIVE WRITING"],
  }),
  ARISTOTLE: makePrefill({
    "07:45": ["PRINCIPLES OF MKTG", "PRINCIPLES OF MKTG", "PRINCIPLES OF MKTG", "PRINCIPLES OF MKTG", "HRGP"],
    "08:45": ["PAGBASA", "PAGBASA", "PAGBASA", "PR1", "PAGBASA"],
    "10:00": ["PR1", "READING & WRITING", "READING & WRITING", "READING & WRITING", "READING & WRITING"],
    "11:00": ["PR1", "STAT", "STAT", "STAT", "STAT"],
    "13:00": ["UCSP", "UCSP", "UCSP", "UCSP", "HOPE"],
    "14:00": ["FABM1", "FABM1", "FABM1", "FABM1", "PHYSCI"],
    "15:00": ["PHYSCI", "PHYSCI", "PHYSCI", "", "PR1"],
  }),
  GRATITUDE: makePrefill({
    "07:45": ["", "", "", "", "FBS"],
    "08:45": ["", "", "", "", "FBS"],
    "10:00": ["", "", "", "", "PERDEV"],
    "11:00": ["", "", "", "", "MIL"],
    "13:00": ["", "", "", "", "IMMERSION"],
    "14:00": ["", "", "", "", "EAPP"],
    "15:00": ["", "", "", "", "3Is"],
    "16:00": ["", "", "", "", "HOPE"],
  }),
  HOPE: makePrefill({
    "07:45": ["PERDEV", "PERDEV", "PERDEV", "PERDEV", "HRGP"],
    "08:45": ["IMMERSION", "IMMERSION", "HOPE", "IMMERSION", "IMMERSION"],
    "10:00": ["EAPP", "MIL", "EAPP", "EAPP", "EAPP"],
    "11:00": ["3Is", "MIL", "3Is", "3Is", "3Is"],
    "13:00": ["FBS", "FBS", "FBS", "MIL", "FBS"],
    "14:00": ["FBS", "FBS", "FBS", "MIL", "FBS"],
  }),
  TRIUMPH: makePrefill({
    "07:45": ["3Is", "3Is", "3Is", "3Is", "HRGP"],
    "08:45": ["PERDEV", "RES.CAP", "RES.CAP", "RES.CAP", "RES.CAP"],
    "10:00": ["GEN.Phy", "GEN.Phy", "PERDEV", "GEN.Phy", "GEN.Phy"],
    "11:00": ["MIL", "MIL", "PERDEV", "MIL", "MIL"],
    "13:00": ["EAPP", "EAPP", "EAPP", "PERDEV", "EAPP"],
    "14:00": ["HOPE", "", "", "", ""],
  }),
  WISDOM: makePrefill({
    "07:45": ["RES.CAP", "RES.CAP", "RES.CAP", "RES.CAP", "HRGP"],
    "08:45": ["GEN.Phy", "GEN.Phy", "GEN.Phy", "GEN.Phy", "MIL"],
    "10:00": ["EAPP", "EAPP", "MIL", "EAPP", "EAPP"],
    "11:00": ["PERDEV", "PERDEV", "MIL", "PERDEV", "PERDEV"],
    "13:00": ["HOPE", "3Is", "3Is", "3Is", "3Is"],
    "14:00": ["MIL", "", "", "", ""],
  }),
  HUMILITY: makePrefill({
    "07:45": ["EAPP", "EAPP", "EAPP", "EAPP", "HRGP"],
    "08:45": ["DRRR", "DRRR", "DRRR", "MIL", "DRRR"],
    "10:00": ["MIL", "PERDEV", "PERDEV", "PERDEV", "PERDEV"],
    "11:00": ["FABM 2", "3Is", "FABM 2", "FABM 2", "FABM 2"],
    "13:00": ["CAREER ADV", "CAREER ADV", "HOPE", "CAREER ADV", "CAREER ADV"],
    "14:00": ["INTRO TO WORLD", "INTRO TO WORLD", "INTRO TO WORLD", "INTRO TO WORLD", "MIL"],
    "15:00": ["3Is", "", "3Is", "3Is", "MIL"],
  }),
  FAITH: makePrefill({
    "07:45": ["CAREER ADV", "CAREER ADV", "CAREER ADV", "CAREER ADV", "HRGP"],
    "08:45": ["EAPP", "EAPP", "EAPP", "DRRR", "EAPP"],
    "10:00": ["INTRO TO WORLD", "INTRO TO WORLD", "DRRR", "INTRO TO WORLD", "INTRO TO WORLD"],
    "11:00": ["PERDEV", "PERDEV", "DRRR", "PERDEV", "PERDEV"],
    "13:00": ["FABM 2", "FABM 2", "FABM 2", "FABM 2", "HOPE"],
    "14:00": ["3Is", "3Is", "MIL", "3Is", "3Is"],
    "15:00": ["MIL", "", "MIL", "MIL", "DRRR"],
  }),
  LOVE: makePrefill({
    "07:45": ["TRENDS", "TRENDS", "TRENDS", "TRENDS", "HRGP"],
    "08:45": ["CAREER ADV", "CAREER ADV", "3Is", "3Is", "CAREER ADV"],
    "10:00": ["3Is", "PERDEV", "PERDEV", "PERDEV", "PERDEV"],
    "11:00": ["EAPP", "EAPP", "3Is", "EAPP", "EAPP"],
    "13:00": ["3Is", "MIL", "MIL", "MIL", "MIL"],
    "14:00": ["", "HOPE", "", "", ""],
  }),
  CHARITY: makePrefill({
    "07:45": ["EAPP", "EAPP", "EAPP", "EAPP", "HRGP"],
    "08:45": ["3Is", "3Is", "3Is", "TRENDS", "HOPE"],
    "10:00": ["MIL", "MIL", "TRENDS", "MIL", "MIL"],
    "11:00": ["PERDEV", "PERDEV", "TRENDS", "PERDEV", "PERDEV"],
    "13:00": ["TRENDS", "CAREER ADV", "CAREER ADV", "CAREER ADV", "CAREER ADV"],
    "14:00": ["", "", "", "3Is", ""],
  }),
  DILIGENCE: makePrefill({
    "07:45": ["MIL", "MIL", "MIL", "MIL", "HRGP"],
    "08:45": ["TRENDS", "TRENDS", "TRENDS", "EAPP", "TRENDS"],
    "10:00": ["PERDEV", "PERDEV", "PERDEV", "HOPE", "PERDEV"],
    "11:00": ["CAREER ADV", "EAPP", "CAREER ADV", "CAREER ADV", "CAREER ADV"],
    "13:00": ["EAPP", "3Is", "3Is", "3Is", "3Is"],
    "14:00": ["EAPP", "", "", "", ""],
  }),
  PERSEVERANCE: makePrefill({
    "07:45": ["PERDEV", "PERDEV", "PERDEV", "PERDEV", "HRGP"],
    "08:45": ["MIL", "MIL", "MIL", "MIL", "CAREER ADV"],
    "10:00": ["EAPP", "EAPP", "HOPE", "EAPP", "EAPP"],
    "11:00": ["3Is", "3Is", "CAREER ADV", "3Is", "3Is"],
    "13:00": ["CAREER ADV", "TRENDS", "TRENDS", "TRENDS", "TRENDS"],
    "14:00": ["CAREER ADV", "", "", "", ""],
  }),
  GENEROSITY: makePrefill({
    "07:45": ["EAPP", "EAPP", "EAPP", "EAPP", "HRGP"],
    "08:45": ["PERDEV", "PERDEV", "PERDEV", "3Is", "PERDEV"],
    "10:00": ["CAREER ADV", "HOPE", "CAREER ADV", "CAREER ADV", "CAREER ADV"],
    "11:00": ["MIL", "MIL", "3Is", "MIL", "MIL"],
    "13:00": ["3Is", "TRENDS", "TRENDS", "TRENDS", "TRENDS"],
    "14:00": ["3Is", "", "", "", ""],
  }),
  PATIENCE: makePrefill({
    "07:45": ["PERDEV", "PERDEV", "PERDEV", "PERDEV", "HRGP"],
    "08:45": ["BSI", "BSI", "BSI", "BSI", "BESR"],
    "10:00": ["BESR", "BESR", "MIL", "MIL", "MIL"],
    "11:00": ["EAPP", "EAPP", "HOPE", "EAPP", "EAPP"],
    "13:00": ["MIL", "3Is", "3Is", "3Is", "3Is"],
    "14:00": ["", "", "BESR", "", ""],
  }),
};

export function findImagePrefillEntries(sectionName: string) {
  const key = (sectionName || "").toUpperCase().replace(/[^A-Z0-9]/g, "");
  // find a prefills entry where key contains the prefills key or vice versa
  const foundKey = Object.keys(imagePrefill).find((k) => key.includes(k) || k.includes(key));
  if (!foundKey) return [];
  return imagePrefill[foundKey] || [];
}

export default imagePrefill;
